#include "help_text.hpp"

namespace perfect6502_debug
{

const char* human_help_text()
{
    return
        "perfect6502_debug help (human)\n"
        "===============================\n"
        "\n"
        "This debugger is a cycle-level helper for the vendored perfect6502\n"
        "netlist emulator. It is not an instruction debugger.\n"
        "\n"
        "Cycle cursor model\n"
        "------------------\n"
        "full cycle = memory halfcycle + cpu halfcycle\n"
        "memory halfcycle: external memory/client side services the pending bus request\n"
        "cpu halfcycle: perfect6502 advances internal CPU state and produces the next request\n"
        "\n"
        "The debugger cursor is always placed before the next halfcycle.\n"
        "boundary=BeforeMemoryHalf means the next halfcycle is cycle_number.M.\n"
        "boundary=BeforeCpuHalf means the next halfcycle is cycle_number.C.\n"
        "In fullcycle-off mode, a full cycle command is valid only at boundary=BeforeMemoryHalf.\n"
        "In fullcycle-on mode, the debugger hides Memory halfcycles and stops at BeforeCpuHalf.\n"
        "The debugger starts in fullcycle-on mode by default.\n"
        "That position shows the real input data for the next CPU halfcycle.\n"
        "Fullcycle transition output keeps bus/memory context separate from CPU semantics:\n"
        "input data is present only for served reads; output addr|data carries write data only for write requests.\n"
        "\n"
        "Commands\n"
        "--------\n"
        "help              print this help\n"
        "help ai           print the AI-oriented help\n"
        "show              print debugger state\n"
        "h | half [n]      execute n halfcycles; default n is 1; unavailable in fullcycle-on mode\n"
        "c | cycle [n]     fullcycle-off: execute n M+C cycles from BeforeMemoryHalf\n"
        "                  fullcycle-on: execute n CPU halfcycles, hiding each following Memory halfcycle\n"
        "fullcycle on      enable CPU-input-boundary fullcycle mode\n"
        "fullcycle off     disable fullcycle mode and allow explicit halfcycle stepping\n"
        "fc on|off         short form for fullcycle on|off\n"
        "u | undo [n]      restore the state saved before the last n state-changing commands\n"
        "irq assert|a      assert IRQ before the next halfcycle\n"
        "irq release|r     release IRQ before the next halfcycle\n"
        "nmi assert|a      assert NMI before the next halfcycle\n"
        "nmi release|r     release NMI before the next halfcycle\n"
        "nmi toggle|t      toggle NMI before the next halfcycle\n"
        "setup <expr>      apply setup input, re-bootstrap perfect6502, and clear undo history\n"
        "q | quit          exit\n"
        "\n"
        "An empty input line repeats the last h, c, t, or u command.\n"
        "IRQ/NMI commands are undoable and print the real perfect6502 input state.\n"
        "\n"
        "Setup input format\n"
        "------------------\n"
        "Letters are case-insensitive. Whitespace is free. Comments start with //\n"
        "and continue to the end of the line. Statements are separated by ';'.\n"
        "The final ';' may be omitted.\n"
        "\n"
        "Register targets:\n"
        "  pc, a, x, y, s, p\n"
        "\n"
        "Memory target:\n"
        "  mem[address] = { byte0, byte1, ... };\n"
        "  mem[address] = byte;\n"
        "\n"
        "Number formats:\n"
        "  123        decimal\n"
        "  0x7b       hexadecimal\n"
        "  b01111011  binary\n"
        "  -54        signed decimal byte value\n"
        "  -0x4a      signed hexadecimal byte value\n"
        "  -b1010     signed binary byte value\n"
        "Signed byte values are accepted for a, x, y, s, p, and memory bytes.\n"
        "They are converted to 8-bit two's-complement values. Addresses and pc\n"
        "must remain unsigned 16-bit values.\n"
        "\n"
        "Defaults\n"
        "--------\n"
        "pc = 0x0200\n"
        "a = 0x00\n"
        "x = 0x00\n"
        "y = 0x00\n"
        "s = 0xfd\n"
        "p = 0x24\n"
        "memory fill = 0xea\n"
        "\n"
        "Example\n"
        "-------\n"
        "setup pc = 0x0200; a = 0x41; p = b00100100; x = -54; y = -0x4a; "
        "mem[0x0200] = { 0x18, 0x69, 0x01, 0xea }; // CLC; ADC #$01; NOP\n"
        "\n";
}

const char* ai_help_text()
{
    return
        "perfect6502_debug help (ai)\n"
        "============================\n"
        "\n"
        "purpose: cycle-level semantic investigation of the vendored perfect6502 netlist emulator\n"
        "not-purpose: instruction-level debugging\n"
        "\n"
        "cycle_definition:\n"
        "  full_cycle: mem_halfcycle + cpu_halfcycle\n"
        "  mem_halfcycle: corresponds to qe6502 client-side bus processing\n"
        "  cpu_halfcycle: corresponds to qe6502_tick()\n"
        "  phase_tracking: external; perfect6502 alternates strictly\n"
        "\n"
        "cursor_model:\n"
        "  cursor_position: always before the next halfcycle\n"
        "  boundary_before_memory_half: outside a full cycle; next halfcycle is cycle_number.M\n"
        "  boundary_before_cpu_half: inside a full cycle; next halfcycle is cycle_number.C\n"
        "  cycle_command_validity_off: valid only at boundary_before_memory_half\n"
        "  fullcycle_on_default: enabled at startup\n"
        "  fullcycle_on_boundary: debugger stops at boundary_before_cpu_half\n"
        "  fullcycle_on_cycle_command: execute CPU halfcycle, capture CPU output bus, secretly execute next Memory halfcycle, capture next CPU input\n"
        "\n"
        "ai_cycle_trace_format:\n"
        "  purpose: compact copy-paste format for comparing full-cycle behavior across cases\n"
        "  one_line_per_completed_cycle: yes\n"
        "  line_shape: cy=<cycle> | in <bus> | pre <regs> | out <bus> | post <regs> | irq=<state> nmi=<state>\n"
        "  in_bus: CPU input at BeforeCpuHalf after the Memory halfcycle has been served\n"
        "  pre_regs: CPU state before the CPU halfcycle\n"
        "  out_bus: bus request left by the CPU halfcycle for the next full cycle\n"
        "  post_regs: CPU state after the CPU halfcycle\n"
        "  pending_read_suffix: use -> ?? (bus=XX, mem=YY) for reads that have not yet been served\n"
        "  read_example: cy=000003 | in R 1001 -> 10 | pre pc=0203 ir=fd a=50 x=01 y=00 s=fd p=25 | out R 0203 -> ?? (bus=10, mem=ea) | post pc=0203 ir=fd a=40 x=01 y=00 s=fd p=25 | irq=rel nmi=rel\n"
        "  write_example: cy=000003 | in W 2000 <= aa | pre pc=0203 ir=8d a=aa x=00 y=00 s=fd p=24 | out R 0203 -> ?? (bus=20, mem=ea) | post pc=0203 ir=8d a=aa x=00 y=00 s=fd p=24 | irq=rel nmi=rel\n"
        "\n"
        "commands:\n"
        "  help: print human help\n"
        "  help ai: print AI help\n"
        "  show: print debugger state\n"
        "  h|half [n]: execute n halfcycles; default 1; unavailable in fullcycle-on mode\n"
        "  c|cycle [n]: fullcycle-off executes n M+C cycles from BeforeMemoryHalf\n"
        "  c|cycle [n]: fullcycle-on executes n CPU halfcycles and hides each following Memory halfcycle\n"
        "  t|trace [n]: fullcycle-on only; execute n cycles and print one compact AI trace line per cycle\n"
        "  fullcycle on|off: switch fullcycle CPU-input-boundary mode\n"
        "  fc on|off: short form for fullcycle on|off\n"
        "  u|undo [n]: restore state saved before the last n state-changing commands\n"
        "  irq assert|a: assert IRQ before the next halfcycle; undoable\n"
        "  irq release|r: release IRQ before the next halfcycle; undoable\n"
        "  nmi assert|a: assert NMI before the next halfcycle; undoable\n"
        "  nmi release|r: release NMI before the next halfcycle; undoable\n"
        "  nmi toggle|t: toggle NMI before the next halfcycle; undoable\n"
        "  setup <expr>: apply setup input; re-bootstrap perfect6502; clear undo history\n"
        "  q|quit: exit\n"
        "  empty_line: repeat the last h, c, t, or u command\n"
        "  interrupt_state_output: irq/nmi state is read back from perfect6502 nodes\n"
        "\n"
        "ai_cycle_trace_format:\n"
        "  line_shape: cy=<cycle> | in <bus> | input=<byte|none> | pre pc=<pc> ir=<ir> a=<a> x=<x> y=<y> s=<s> p=<p> | out <bus> | output=<addr|data> | post pc=<pc> ir=<ir> a=<a> x=<x> y=<y> s=<s> p=<p> | irq=<rel|asrt> nmi=<rel|asrt>\n"
        "  input_semantics: input=<byte> only for served reads; input=none for served writes\n"
        "  output_semantics: output=<addr>|none for read requests; output=<addr>|<byte> for write requests\n"
        "  bus_context: bus and mem fields stay separate from semantic input/output fields\n"
        "  read_output_bus: out R <addr> -> pending mem=<memory[address]>\n"
        "  write_output_bus: out W <addr> <= <byte> mem=<memory[address-before-service]>\n"
        "  use_case: compact copy/pasteable trace for AI-assisted analysis\n"
        "\n"
        "setup_input:\n"
        "  case: ascii case-insensitive; input is normalized to lowercase\n"
        "  comments: // until end of line\n"
        "  statement_separator: semicolon required between statements\n"
        "  final_semicolon: optional\n"
        "  register_targets: pc,a,x,y,s,p\n"
        "  memory_target: mem only\n"
        "  memory_forms:\n"
        "    mem[addr]={byte0,byte1,...};\n"
        "    mem[addr]=byte;\n"
        "  repeated_targets: allowed; applied left-to-right; last write wins on overlap\n"
        "  numbers:\n"
        "    decimal: [0-9]+\n"
        "    hex: 0x[0-9a-f]+\n"
        "    binary: b[01]+\n"
        "    signed_decimal_byte: -[0-9]+\n"
        "    signed_hex_byte: -0x[0-9a-f]+\n"
        "    signed_binary_byte: -b[01]+\n"
        "  signed_byte_conversion: two's complement, e.g. -1 becomes 0xff\n"
        "  signed_byte_contexts: a,x,y,s,p,mem bytes\n"
        "  unsigned_only_contexts: pc,mem address\n"
        "  ranges:\n"
        "    pc: 0..65535\n"
        "    mem address: 0..65535\n"
        "    a,x,y,s,p,mem bytes: -128..255\n"
        "  empty_memory_list: error\n"
        "  wraparound_on_out_of_range: no; parse error\n"
        "\n"
        "defaults:\n"
        "  pc: 0x0200\n"
        "  a: 0x00\n"
        "  x: 0x00\n"
        "  y: 0x00\n"
        "  s: 0xfd\n"
        "  p: 0x24\n"
        "  memory_fill: 0xea\n"
        "\n"
        "example:\n"
        "  setup pc=0x0200; a=0x41; x=-54; y=-0x4a; s=0xfd; p=b00100100; "
        "mem[0x0200]={0x18,0x69,0x01,0xea};\n"
        "\n";
}

} // namespace perfect6502_debug
