// This file was automatically generated by `opcode_autogen.py`.
// Manual modifications are discouraged and may lead to unintended errors.
// Contains opcode handler declarations and metadata used by the emulator.

#ifndef QE6502_CMOS_FW_H__
#define QE6502_CMOS_FW_H__

#include "qe6502_inline.h"


INSTR_RETTYPE qe6502_cycle_t
cmos_opcode_dispatcher( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_fetch_opcode( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_jmp_absolute( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_r_absolute( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_rw_absolute( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_w_absolute( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_r_absolute_x( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_rw_absolute_x( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_rw_absolute_x_short( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_w_absolute_x( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_r_absolute_y( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_w_absolute_y( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_r_immediate( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_r_indexed_x( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_w_indexed_x( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_r_indexed_y( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_w_indexed_y( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_jmp_indirect( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_r_zeropage( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_rw_zeropage( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_w_zeropage( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_r_zeropage_x( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_rw_zeropage_x( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_w_zeropage_x( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_r_zeropage_y( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_w_zeropage_y( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t  // ADC - Add with Carry
cmos_instr_ADC( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t
cmos_instr_ADC_Immediate( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t  // AND - Logical AND
cmos_instr_AND( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // ASL - Arithmetic Shift Left
cmos_instr_ASL( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // ASL - Arithmetic Shift Left
cmos_instr_ASL_accumulator( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // BCC - Branch if Carry Clear
cmos_instr_BCC( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // BCS - Branch if Carry Set
cmos_instr_BCS( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // BEQ - Branch if Equal
cmos_instr_BEQ( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // BIT - Bit Test
cmos_instr_BIT( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // BMI - Branch if Minus
cmos_instr_BMI( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // BNE - Branch if Not Equal
cmos_instr_BNE( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // BPL - Branch if Positive
cmos_instr_BPL( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // BRK - Force Interrupt
cmos_instr_BRK( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // BRK - Force Interrupt Finalizer
cmos_instr_BRK_finalize( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t  // BVC - Branch if Overflow Clear
cmos_instr_BVC( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // BVS - Branch if Overflow Set
cmos_instr_BVS( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // CLC - Clear Carry Flag
cmos_instr_CLC( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // CLD - Clear Decimal Mode
cmos_instr_CLD( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // CLI - Clear Interrupt Disable
cmos_instr_CLI( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // CLV - Clear Overflow Flag
cmos_instr_CLV( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // CMP - Compare
cmos_instr_CMP( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // CPX - Compare X Register
cmos_instr_CPX( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // CPY - Compare Y Register
cmos_instr_CPY( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // DEC - Decrement Memory
cmos_instr_DEC( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // DEX - Decrement X Register
cmos_instr_DEX( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // DEY - Decrement Y Register
cmos_instr_DEY( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // EOR - Exclusive OR
cmos_instr_EOR( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // INC - Increment Memory
cmos_instr_INC( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // INX - Increment X Register
cmos_instr_INX( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // INY - Increment Y Register
cmos_instr_INY( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // JMP - Jump
cmos_instr_JMP( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // JSR - Jump to Subroutine
cmos_instr_JSR( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // LDA - Load Accumulator
cmos_instr_LDA( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // LDX - Load X Register
cmos_instr_LDX( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // LDY - Load Y Register
cmos_instr_LDY( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // LSR - Logical Shift Right
cmos_instr_LSR( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // LSR - Logical Shift Right
cmos_instr_LSR_accumulator( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // NOP - No Operation
cmos_instr_NOP( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // ORA - Logical Inclusive OR
cmos_instr_ORA( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // PHA - Push Accumulator
cmos_instr_PHA( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // PHP - Push Processor Status
cmos_instr_PHP( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // PLA - Pull Accumulator
cmos_instr_PLA( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // PLP - Pull Processor Status
cmos_instr_PLP( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // ROL - Rotate Left
cmos_instr_ROL( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // ROL - Rotate Left
cmos_instr_ROL_accumulator( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // ROR - Rotate Right
cmos_instr_ROR( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // ROR - Rotate Right
cmos_instr_ROR_accumulator( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // RTI - Return from Interrupt
cmos_instr_RTI( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // RTS - Return from Subroutine
cmos_instr_RTS( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // SBC - Subtract with Carry
cmos_instr_SBC( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t
cmos_instr_SBC_Immediate( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t  // SEC - Set Carry Flag
cmos_instr_SEC( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // SED - Set Decimal Flag
cmos_instr_SED( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // SEI - Set Interrupt Disable
cmos_instr_SEI( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // STA - Store Accumulator
cmos_instr_STA( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // STX - Store X Register
cmos_instr_STX( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // STY - Store Y Register
cmos_instr_STY( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // TAX - Transfer Accumulator to X
cmos_instr_TAX( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // TAY - Transfer Accumulator to Y
cmos_instr_TAY( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // TSX - Transfer Stack Pointer to X
cmos_instr_TSX( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // TXA - Transfer X to Accumulator
cmos_instr_TXA( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // TXS - Transfer X to Stack Pointer
cmos_instr_TXS( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // TYA - Transfer Y to Accumulator
cmos_instr_TYA( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

// nes
INSTR_RETTYPE qe6502_cycle_t // ADC - Add with Carry, decimal disabled
cmos_instr_ADC_impl_bin( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t // SBC - Subtract with Carry, decimal disabled
cmos_instr_SBC_impl_bin( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

// cmos
INSTR_RETTYPE qe6502_cycle_t
cmos_pre_r_indirect_zp( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_w_indirect_zp( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t  // BIT - Bit Test CMOS immediate mode
cmos_instr_BIT_immediate( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t  // DEC - Decrement Memory accumulator CMOS
cmos_instr_DEC_accumulator( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t  // INC - Increment Memory accumulator CMOS
cmos_instr_INC_accumulator( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t  // BCA - Branch if Always CMOS
cmos_instr_BRA( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t  // Push Register X CMOS
cmos_instr_PHX( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t  // Push Register Y CMOS
cmos_instr_PHY( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t  // Pull Register X CMSO
cmos_instr_PLX( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t  // Pull Register Y CMSO
cmos_instr_PLY( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t  // Store Zero CMOS
cmos_instr_STZ( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t  // Test and Reset Bits CMOS
cmos_instr_TRB( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t  // Test and Set Bits CMOS
cmos_instr_TSB( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t  // BRK - Force Interrupt Finalizer CMOS
cmos_instr_BRK_finalize( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t  // BBR/BBS - Branch on Bit Reset(BBR) or Set(BBS) CMOS
cmos_pre_rw_bbr_zeropage_relative( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t  // BBR/BBS - Branch on Bit Reset(BBR) or Set(BBS) CMOS
cmos_pre_rw_bbs_zeropage_relative( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t  // RMB SMB - Reset(RMB) or Set(SMB) Memory Bit CMOS
cmos_instr_RMB_SMB( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t  // Illegal NOP - No Operation
cmos_instr_ILLEGAL_NOP( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t  // CMOS
cmos_pre_jmp_indirect_x( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_instr_0x5C_0xDC_0xFC( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_pre_rw_zeropage_RMB_SMB( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
cmos_instr_ILLEGAL_NOP_st_xXf( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t  // irq handle
cmos_irq( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // nmi handle
cmos_nmi( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

#endif // QE6502_CMOS_FW_H__

