// This file was automatically generated by `opcode_autogen.py`.
// Manual modifications are discouraged and may lead to unintended errors.
// Contains opcode handler declarations and metadata used by the emulator.

#ifndef QE_NMOS_FW_H__
#define QE_NMOS_FW_H__

#include "6502_inline.h"

INSTR_RETTYPE qe6502_cycle_t
halt( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
nmos_opcode_dispatcher( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
nmos_pre_jmp_absolute( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
nmos_pre_r_absolute( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
nmos_pre_rw_absolute( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
nmos_pre_w_absolute( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
nmos_pre_r_absolute_x( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
nmos_pre_rw_absolute_x( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
nmos_pre_w_absolute_x( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
nmos_pre_r_absolute_y( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
nmos_pre_w_absolute_y( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
nmos_pre_r_immediate( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
nmos_pre_r_indexed_x( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
nmos_pre_w_indexed_x( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
nmos_pre_r_indexed_y( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
nmos_pre_w_indexed_y( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
nmos_pre_jmp_indirect( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
nmos_pre_r_zeropage( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
nmos_pre_rw_zeropage( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
nmos_pre_w_zeropage( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
nmos_pre_r_zeropage_x( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
nmos_pre_rw_zeropage_x( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
nmos_pre_w_zeropage_x( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
nmos_pre_r_zeropage_y( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t
nmos_pre_w_zeropage_y( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t  //
nmos_instr_ILLEGAL( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // ADC - Add with Carry
nmos_instr_ADC( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // AND - Logical AND
nmos_instr_AND( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // ASL - Arithmetic Shift Left
nmos_instr_ASL( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // ASL - Arithmetic Shift Left
nmos_instr_ASL_accumulator( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // BCC - Branch if Carry Clear
nmos_instr_BCC( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // BCS - Branch if Carry Set
nmos_instr_BCS( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // BEQ - Branch if Equal
nmos_instr_BEQ( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // BIT - Bit Test
nmos_instr_BIT( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // BMI - Branch if Minus
nmos_instr_BMI( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // BNE - Branch if Not Equal
nmos_instr_BNE( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // BPL - Branch if Positive
nmos_instr_BPL( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // BRK - Force Interrupt
nmos_instr_BRK( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // BRK - Force Interrupt Finalizer
nmos_instr_BRK_finalize( INSTR_ARGS qe6502_t* QE_RESTRICT cpu );

INSTR_RETTYPE qe6502_cycle_t  // BVC - Branch if Overflow Clear
nmos_instr_BVC( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // BVS - Branch if Overflow Set
nmos_instr_BVS( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // CLC - Clear Carry Flag
nmos_instr_CLC( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // CLD - Clear Decimal Mode
nmos_instr_CLD( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // CLI - Clear Interrupt Disable
nmos_instr_CLI( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // CLV - Clear Overflow Flag
nmos_instr_CLV( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // CMP - Compare
nmos_instr_CMP( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // CPX - Compare X Register
nmos_instr_CPX( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // CPY - Compare Y Register
nmos_instr_CPY( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // DEC - Decrement Memory
nmos_instr_DEC( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // DEX - Decrement X Register
nmos_instr_DEX( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // DEY - Decrement Y Register
nmos_instr_DEY( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // EOR - Exclusive OR
nmos_instr_EOR( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // INC - Increment Memory
nmos_instr_INC( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // INX - Increment X Register
nmos_instr_INX( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // INY - Increment Y Register
nmos_instr_INY( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // JMP - Jump
nmos_instr_JMP( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // JSR - Jump to Subroutine
nmos_instr_JSR( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // LDA - Load Accumulator
nmos_instr_LDA( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // LDX - Load X Register
nmos_instr_LDX( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // LDY - Load Y Register
nmos_instr_LDY( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // LSR - Logical Shift Right
nmos_instr_LSR( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // LSR - Logical Shift Right
nmos_instr_LSR_accumulator( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // NOP - No Operation
nmos_instr_NOP( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // ORA - Logical Inclusive OR
nmos_instr_ORA( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // PHA - Push Accumulator
nmos_instr_PHA( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // PHP - Push Processor Status
nmos_instr_PHP( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // PLA - Pull Accumulator
nmos_instr_PLA( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // PLP - Pull Processor Status
nmos_instr_PLP( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // ROL - Rotate Left
nmos_instr_ROL( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // ROL - Rotate Left
nmos_instr_ROL_accumulator( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // ROR - Rotate Right
nmos_instr_ROR( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // ROR - Rotate Right
nmos_instr_ROR_accumulator( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // RTI - Return from Interrupt
nmos_instr_RTI( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // RTS - Return from Subroutine
nmos_instr_RTS( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // SBC - Subtract with Carry
nmos_instr_SBC( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // SEC - Set Carry Flag
nmos_instr_SEC( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // SED - Set Decimal Flag
nmos_instr_SED( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // SEI - Set Interrupt Disable
nmos_instr_SEI( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // STA - Store Accumulator
nmos_instr_STA( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // STX - Store X Register
nmos_instr_STX( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // STY - Store Y Register
nmos_instr_STY( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // TAX - Transfer Accumulator to X
nmos_instr_TAX( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // TAY - Transfer Accumulator to Y
nmos_instr_TAY( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // TSX - Transfer Stack Pointer to X
nmos_instr_TSX( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // TXA - Transfer X to Accumulator
nmos_instr_TXA( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // TXS - Transfer X to Stack Pointer
nmos_instr_TXS( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // TYA - Transfer Y to Accumulator
nmos_instr_TYA( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // irq handle
nmos_irq( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

INSTR_RETTYPE qe6502_cycle_t  // nmi handle
nmos_nmi( INSTR_ARGS qe6502_t* QE_RESTRICT cpu ) ;

#endif // QE_NMOS_FW_H__

