// This file was automatically generated by `opcode_autogen.py`.
// Manual modifications are discouraged and may lead to unintended errors.
// Contains opcode handler declarations and metadata used by the emulator.

#ifndef QE6502_NMOS_OPCODES_H__
#define QE6502_NMOS_OPCODES_H__

#include "qe6502_nmos_fw.h"

static const qe6502_model_t nmos_model = {
.opcodes =
{
    /*----------------------------------------------------*/
    //  BRK, Force Interrupt
    //  class: Special
    //  Opcode: 0x00(  0), Bytes: 1, Mode: Implied
    //
    {   nmos_instr_BRK, nmos_instr_BRK_finalize },
    /*----------------------------------------------------*/
    //  ORA, Logical Inclusive OR
    //  class: Reader
    //  Opcode: 0x01(  1), Bytes: 2, Mode: Indexed_X
    //
    {   nmos_pre_r_indexed_x, nmos_instr_ORA },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x02(2  )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x03(3  )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x04(4  )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  ORA, Logical Inclusive OR
    //  class: Reader
    //  Opcode: 0x05(  5), Bytes: 2, Mode: ZeroPage
    //
    {   nmos_pre_r_zeropage, nmos_instr_ORA },
    /*----------------------------------------------------*/
    //  ASL, Arithmetic Shift Left
    //  class: ReaderWriter
    //  Opcode: 0x06(  6), Bytes: 2, Mode: ZeroPage
    //
    {   nmos_pre_rw_zeropage, nmos_instr_ASL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x07(7  )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  PHP, Push Processor Status
    //  class: Special
    //  Opcode: 0x08(  8), Bytes: 1, Mode: Implied
    //
    {   nmos_instr_PHP, nmos_instr_PHP },
    /*----------------------------------------------------*/
    //  ORA, Logical Inclusive OR
    //  class: Reader
    //  Opcode: 0x09(  9), Bytes: 2, Mode: Immediate
    //
    {   nmos_pre_r_immediate, nmos_instr_ORA },
    /*----------------------------------------------------*/
    //  ASL, Arithmetic Shift Left
    //  class: ReaderWriter
    //  Opcode: 0x0A( 10), Bytes: 1, Mode: Accumulator
    //
    {   nmos_instr_ASL_accumulator, nmos_instr_ASL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x0B(11 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x0C(12 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  ORA, Logical Inclusive OR
    //  class: Reader
    //  Opcode: 0x0D( 13), Bytes: 3, Mode: Absolute
    //
    {   nmos_pre_r_absolute, nmos_instr_ORA },
    /*----------------------------------------------------*/
    //  ASL, Arithmetic Shift Left
    //  class: ReaderWriter
    //  Opcode: 0x0E( 14), Bytes: 3, Mode: Absolute
    //
    {   nmos_pre_rw_absolute, nmos_instr_ASL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x0F(15 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  BPL, Branch if Positive
    //  class: BranchIf
    //  Opcode: 0x10( 16), Bytes: 2, Mode: Relative
    //
    {   nmos_instr_BPL, nmos_instr_BPL },
    /*----------------------------------------------------*/
    //  ORA, Logical Inclusive OR
    //  class: Reader
    //  Opcode: 0x11( 17), Bytes: 2, Mode: Indexed_Y
    //
    {   nmos_pre_r_indexed_y, nmos_instr_ORA },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x12(18 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x13(19 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x14(20 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  ORA, Logical Inclusive OR
    //  class: Reader
    //  Opcode: 0x15( 21), Bytes: 2, Mode: ZeroPage_X
    //
    {   nmos_pre_r_zeropage_x, nmos_instr_ORA },
    /*----------------------------------------------------*/
    //  ASL, Arithmetic Shift Left
    //  class: ReaderWriter
    //  Opcode: 0x16( 22), Bytes: 2, Mode: ZeroPage_X
    //
    {   nmos_pre_rw_zeropage_x, nmos_instr_ASL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x17(23 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  CLC, Clear Carry Flag
    //  class: Regs
    //  Opcode: 0x18( 24), Bytes: 1, Mode: Implied
    //
    {   nmos_instr_CLC, nmos_instr_CLC },
    /*----------------------------------------------------*/
    //  ORA, Logical Inclusive OR
    //  class: Reader
    //  Opcode: 0x19( 25), Bytes: 3, Mode: Absolute_Y
    //
    {   nmos_pre_r_absolute_y, nmos_instr_ORA },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x1A(26 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x1B(27 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x1C(28 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  ORA, Logical Inclusive OR
    //  class: Reader
    //  Opcode: 0x1D( 29), Bytes: 3, Mode: Absolute_X
    //
    {   nmos_pre_r_absolute_x, nmos_instr_ORA },
    /*----------------------------------------------------*/
    //  ASL, Arithmetic Shift Left
    //  class: ReaderWriter
    //  Opcode: 0x1E( 30), Bytes: 3, Mode: Absolute_X
    //
    {   nmos_pre_rw_absolute_x, nmos_instr_ASL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x1F(31 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  JSR, Jump to Subroutine
    //  class: Special
    //  Opcode: 0x20( 32), Bytes: 3, Mode: Absolute
    //
    {   nmos_instr_JSR, nmos_instr_JSR },
    /*----------------------------------------------------*/
    //  AND, Logical AND
    //  class: Reader
    //  Opcode: 0x21( 33), Bytes: 2, Mode: Indexed_X
    //
    {   nmos_pre_r_indexed_x, nmos_instr_AND },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x22(34 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x23(35 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  BIT, Bit Test
    //  class: Reader
    //  Opcode: 0x24( 36), Bytes: 2, Mode: ZeroPage
    //
    {   nmos_pre_r_zeropage, nmos_instr_BIT },
    /*----------------------------------------------------*/
    //  AND, Logical AND
    //  class: Reader
    //  Opcode: 0x25( 37), Bytes: 2, Mode: ZeroPage
    //
    {   nmos_pre_r_zeropage, nmos_instr_AND },
    /*----------------------------------------------------*/
    //  ROL, Rotate Left
    //  class: ReaderWriter
    //  Opcode: 0x26( 38), Bytes: 2, Mode: ZeroPage
    //
    {   nmos_pre_rw_zeropage, nmos_instr_ROL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x27(39 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  PLP, Pull Processor Status
    //  class: Special
    //  Opcode: 0x28( 40), Bytes: 1, Mode: Implied
    //
    {   nmos_instr_PLP, nmos_instr_PLP },
    /*----------------------------------------------------*/
    //  AND, Logical AND
    //  class: Reader
    //  Opcode: 0x29( 41), Bytes: 2, Mode: Immediate
    //
    {   nmos_pre_r_immediate, nmos_instr_AND },
    /*----------------------------------------------------*/
    //  ROL, Rotate Left
    //  class: ReaderWriter
    //  Opcode: 0x2A( 42), Bytes: 1, Mode: Accumulator
    //
    {   nmos_instr_ROL_accumulator, nmos_instr_ROL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x2B(43 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  BIT, Bit Test
    //  class: Reader
    //  Opcode: 0x2C( 44), Bytes: 3, Mode: Absolute
    //
    {   nmos_pre_r_absolute, nmos_instr_BIT },
    /*----------------------------------------------------*/
    //  AND, Logical AND
    //  class: Reader
    //  Opcode: 0x2D( 45), Bytes: 3, Mode: Absolute
    //
    {   nmos_pre_r_absolute, nmos_instr_AND },
    /*----------------------------------------------------*/
    //  ROL, Rotate Left
    //  class: ReaderWriter
    //  Opcode: 0x2E( 46), Bytes: 3, Mode: Absolute
    //
    {   nmos_pre_rw_absolute, nmos_instr_ROL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x2F(47 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  BMI, Branch if Minus
    //  class: BranchIf
    //  Opcode: 0x30( 48), Bytes: 2, Mode: Relative
    //
    {   nmos_instr_BMI, nmos_instr_BMI },
    /*----------------------------------------------------*/
    //  AND, Logical AND
    //  class: Reader
    //  Opcode: 0x31( 49), Bytes: 2, Mode: Indexed_Y
    //
    {   nmos_pre_r_indexed_y, nmos_instr_AND },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x32(50 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x33(51 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x34(52 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  AND, Logical AND
    //  class: Reader
    //  Opcode: 0x35( 53), Bytes: 2, Mode: ZeroPage_X
    //
    {   nmos_pre_r_zeropage_x, nmos_instr_AND },
    /*----------------------------------------------------*/
    //  ROL, Rotate Left
    //  class: ReaderWriter
    //  Opcode: 0x36( 54), Bytes: 2, Mode: ZeroPage_X
    //
    {   nmos_pre_rw_zeropage_x, nmos_instr_ROL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x37(55 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  SEC, Set Carry Flag
    //  class: Regs
    //  Opcode: 0x38( 56), Bytes: 1, Mode: Implied
    //
    {   nmos_instr_SEC, nmos_instr_SEC },
    /*----------------------------------------------------*/
    //  AND, Logical AND
    //  class: Reader
    //  Opcode: 0x39( 57), Bytes: 3, Mode: Absolute_Y
    //
    {   nmos_pre_r_absolute_y, nmos_instr_AND },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x3A(58 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x3B(59 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x3C(60 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  AND, Logical AND
    //  class: Reader
    //  Opcode: 0x3D( 61), Bytes: 3, Mode: Absolute_X
    //
    {   nmos_pre_r_absolute_x, nmos_instr_AND },
    /*----------------------------------------------------*/
    //  ROL, Rotate Left
    //  class: ReaderWriter
    //  Opcode: 0x3E( 62), Bytes: 3, Mode: Absolute_X
    //
    {   nmos_pre_rw_absolute_x, nmos_instr_ROL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x3F(63 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  RTI, Return from Interrupt
    //  class: Special
    //  Opcode: 0x40( 64), Bytes: 1, Mode: Implied
    //
    {   nmos_instr_RTI, nmos_instr_RTI },
    /*----------------------------------------------------*/
    //  EOR, Exclusive OR
    //  class: Reader
    //  Opcode: 0x41( 65), Bytes: 2, Mode: Indexed_X
    //
    {   nmos_pre_r_indexed_x, nmos_instr_EOR },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x42(66 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x43(67 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x44(68 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  EOR, Exclusive OR
    //  class: Reader
    //  Opcode: 0x45( 69), Bytes: 2, Mode: ZeroPage
    //
    {   nmos_pre_r_zeropage, nmos_instr_EOR },
    /*----------------------------------------------------*/
    //  LSR, Logical Shift Right
    //  class: ReaderWriter
    //  Opcode: 0x46( 70), Bytes: 2, Mode: ZeroPage
    //
    {   nmos_pre_rw_zeropage, nmos_instr_LSR },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x47(71 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  PHA, Push Accumulator
    //  class: Special
    //  Opcode: 0x48( 72), Bytes: 1, Mode: Implied
    //
    {   nmos_instr_PHA, nmos_instr_PHA },
    /*----------------------------------------------------*/
    //  EOR, Exclusive OR
    //  class: Reader
    //  Opcode: 0x49( 73), Bytes: 2, Mode: Immediate
    //
    {   nmos_pre_r_immediate, nmos_instr_EOR },
    /*----------------------------------------------------*/
    //  LSR, Logical Shift Right
    //  class: ReaderWriter
    //  Opcode: 0x4A( 74), Bytes: 1, Mode: Accumulator
    //
    {   nmos_instr_LSR_accumulator, nmos_instr_LSR },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x4B(75 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  JMP, Jump
    //  class: Jmp
    //  Opcode: 0x4C( 76), Bytes: 3, Mode: Absolute
    //
    {   nmos_pre_jmp_absolute, nmos_instr_JMP },
    /*----------------------------------------------------*/
    //  EOR, Exclusive OR
    //  class: Reader
    //  Opcode: 0x4D( 77), Bytes: 3, Mode: Absolute
    //
    {   nmos_pre_r_absolute, nmos_instr_EOR },
    /*----------------------------------------------------*/
    //  LSR, Logical Shift Right
    //  class: ReaderWriter
    //  Opcode: 0x4E( 78), Bytes: 3, Mode: Absolute
    //
    {   nmos_pre_rw_absolute, nmos_instr_LSR },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x4F(79 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  BVC, Branch if Overflow Clear
    //  class: BranchIf
    //  Opcode: 0x50( 80), Bytes: 2, Mode: Relative
    //
    {   nmos_instr_BVC, nmos_instr_BVC },
    /*----------------------------------------------------*/
    //  EOR, Exclusive OR
    //  class: Reader
    //  Opcode: 0x51( 81), Bytes: 2, Mode: Indexed_Y
    //
    {   nmos_pre_r_indexed_y, nmos_instr_EOR },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x52(82 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x53(83 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x54(84 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  EOR, Exclusive OR
    //  class: Reader
    //  Opcode: 0x55( 85), Bytes: 2, Mode: ZeroPage_X
    //
    {   nmos_pre_r_zeropage_x, nmos_instr_EOR },
    /*----------------------------------------------------*/
    //  LSR, Logical Shift Right
    //  class: ReaderWriter
    //  Opcode: 0x56( 86), Bytes: 2, Mode: ZeroPage_X
    //
    {   nmos_pre_rw_zeropage_x, nmos_instr_LSR },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x57(87 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  CLI, Clear Interrupt Disable
    //  class: Regs
    //  Opcode: 0x58( 88), Bytes: 1, Mode: Implied
    //
    {   nmos_instr_CLI, nmos_instr_CLI },
    /*----------------------------------------------------*/
    //  EOR, Exclusive OR
    //  class: Reader
    //  Opcode: 0x59( 89), Bytes: 3, Mode: Absolute_Y
    //
    {   nmos_pre_r_absolute_y, nmos_instr_EOR },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x5A(90 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x5B(91 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x5C(92 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  EOR, Exclusive OR
    //  class: Reader
    //  Opcode: 0x5D( 93), Bytes: 3, Mode: Absolute_X
    //
    {   nmos_pre_r_absolute_x, nmos_instr_EOR },
    /*----------------------------------------------------*/
    //  LSR, Logical Shift Right
    //  class: ReaderWriter
    //  Opcode: 0x5E( 94), Bytes: 3, Mode: Absolute_X
    //
    {   nmos_pre_rw_absolute_x, nmos_instr_LSR },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x5F(95 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  RTS, Return from Subroutine
    //  class: Special
    //  Opcode: 0x60( 96), Bytes: 1, Mode: Implied
    //
    {   nmos_instr_RTS, nmos_instr_RTS },
    /*----------------------------------------------------*/
    //  ADC, Add with Carry
    //  class: Reader
    //  Opcode: 0x61( 97), Bytes: 2, Mode: Indexed_X
    //
    {   nmos_pre_r_indexed_x, nmos_instr_ADC },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x62(98 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x63(99 )
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x64(100)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  ADC, Add with Carry
    //  class: Reader
    //  Opcode: 0x65(101), Bytes: 2, Mode: ZeroPage
    //
    {   nmos_pre_r_zeropage, nmos_instr_ADC },
    /*----------------------------------------------------*/
    //  ROR, Rotate Right
    //  class: ReaderWriter
    //  Opcode: 0x66(102), Bytes: 2, Mode: ZeroPage
    //
    {   nmos_pre_rw_zeropage, nmos_instr_ROR },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x67(103)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  PLA, Pull Accumulator
    //  class: Special
    //  Opcode: 0x68(104), Bytes: 1, Mode: Implied
    //
    {   nmos_instr_PLA, nmos_instr_PLA },
    /*----------------------------------------------------*/
    //  ADC, Add with Carry
    //  class: Reader
    //  Opcode: 0x69(105), Bytes: 2, Mode: Immediate
    //
    {   nmos_pre_r_immediate, nmos_instr_ADC },
    /*----------------------------------------------------*/
    //  ROR, Rotate Right
    //  class: ReaderWriter
    //  Opcode: 0x6A(106), Bytes: 1, Mode: Accumulator
    //
    {   nmos_instr_ROR_accumulator, nmos_instr_ROR },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x6B(107)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  JMP, Jump
    //  class: Jmp
    //  Opcode: 0x6C(108), Bytes: 3, Mode: Indirect
    //
    {   nmos_pre_jmp_indirect, nmos_instr_JMP },
    /*----------------------------------------------------*/
    //  ADC, Add with Carry
    //  class: Reader
    //  Opcode: 0x6D(109), Bytes: 3, Mode: Absolute
    //
    {   nmos_pre_r_absolute, nmos_instr_ADC },
    /*----------------------------------------------------*/
    //  ROR, Rotate Right
    //  class: ReaderWriter
    //  Opcode: 0x6E(110), Bytes: 3, Mode: Absolute
    //
    {   nmos_pre_rw_absolute, nmos_instr_ROR },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x6F(111)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  BVS, Branch if Overflow Set
    //  class: BranchIf
    //  Opcode: 0x70(112), Bytes: 2, Mode: Relative
    //
    {   nmos_instr_BVS, nmos_instr_BVS },
    /*----------------------------------------------------*/
    //  ADC, Add with Carry
    //  class: Reader
    //  Opcode: 0x71(113), Bytes: 2, Mode: Indexed_Y
    //
    {   nmos_pre_r_indexed_y, nmos_instr_ADC },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x72(114)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x73(115)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x74(116)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  ADC, Add with Carry
    //  class: Reader
    //  Opcode: 0x75(117), Bytes: 2, Mode: ZeroPage_X
    //
    {   nmos_pre_r_zeropage_x, nmos_instr_ADC },
    /*----------------------------------------------------*/
    //  ROR, Rotate Right
    //  class: ReaderWriter
    //  Opcode: 0x76(118), Bytes: 2, Mode: ZeroPage_X
    //
    {   nmos_pre_rw_zeropage_x, nmos_instr_ROR },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x77(119)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  SEI, Set Interrupt Disable
    //  class: Regs
    //  Opcode: 0x78(120), Bytes: 1, Mode: Implied
    //
    {   nmos_instr_SEI, nmos_instr_SEI },
    /*----------------------------------------------------*/
    //  ADC, Add with Carry
    //  class: Reader
    //  Opcode: 0x79(121), Bytes: 3, Mode: Absolute_Y
    //
    {   nmos_pre_r_absolute_y, nmos_instr_ADC },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x7A(122)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x7B(123)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x7C(124)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  ADC, Add with Carry
    //  class: Reader
    //  Opcode: 0x7D(125), Bytes: 3, Mode: Absolute_X
    //
    {   nmos_pre_r_absolute_x, nmos_instr_ADC },
    /*----------------------------------------------------*/
    //  ROR, Rotate Right
    //  class: ReaderWriter
    //  Opcode: 0x7E(126), Bytes: 3, Mode: Absolute_X
    //
    {   nmos_pre_rw_absolute_x, nmos_instr_ROR },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x7F(127)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x80(128)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  STA, Store Accumulator
    //  class: Writer
    //  Opcode: 0x81(129), Bytes: 2, Mode: Indexed_X
    //
    {   nmos_pre_w_indexed_x, nmos_instr_STA },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x82(130)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x83(131)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  STY, Store Y Register
    //  class: Writer
    //  Opcode: 0x84(132), Bytes: 2, Mode: ZeroPage
    //
    {   nmos_pre_w_zeropage, nmos_instr_STY },
    /*----------------------------------------------------*/
    //  STA, Store Accumulator
    //  class: Writer
    //  Opcode: 0x85(133), Bytes: 2, Mode: ZeroPage
    //
    {   nmos_pre_w_zeropage, nmos_instr_STA },
    /*----------------------------------------------------*/
    //  STX, Store X Register
    //  class: Writer
    //  Opcode: 0x86(134), Bytes: 2, Mode: ZeroPage
    //
    {   nmos_pre_w_zeropage, nmos_instr_STX },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x87(135)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  DEY, Decrement Y Register
    //  class: Regs
    //  Opcode: 0x88(136), Bytes: 1, Mode: Implied
    //
    {   nmos_instr_DEY, nmos_instr_DEY },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x89(137)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  TXA, Transfer X to Accumulator
    //  class: Regs
    //  Opcode: 0x8A(138), Bytes: 1, Mode: Implied
    //
    {   nmos_instr_TXA, nmos_instr_TXA },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x8B(139)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  STY, Store Y Register
    //  class: Writer
    //  Opcode: 0x8C(140), Bytes: 3, Mode: Absolute
    //
    {   nmos_pre_w_absolute, nmos_instr_STY },
    /*----------------------------------------------------*/
    //  STA, Store Accumulator
    //  class: Writer
    //  Opcode: 0x8D(141), Bytes: 3, Mode: Absolute
    //
    {   nmos_pre_w_absolute, nmos_instr_STA },
    /*----------------------------------------------------*/
    //  STX, Store X Register
    //  class: Writer
    //  Opcode: 0x8E(142), Bytes: 3, Mode: Absolute
    //
    {   nmos_pre_w_absolute, nmos_instr_STX },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x8F(143)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  BCC, Branch if Carry Clear
    //  class: BranchIf
    //  Opcode: 0x90(144), Bytes: 2, Mode: Relative
    //
    {   nmos_instr_BCC, nmos_instr_BCC },
    /*----------------------------------------------------*/
    //  STA, Store Accumulator
    //  class: Writer
    //  Opcode: 0x91(145), Bytes: 2, Mode: Indexed_Y
    //
    {   nmos_pre_w_indexed_y, nmos_instr_STA },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x92(146)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x93(147)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  STY, Store Y Register
    //  class: Writer
    //  Opcode: 0x94(148), Bytes: 2, Mode: ZeroPage_X
    //
    {   nmos_pre_w_zeropage_x, nmos_instr_STY },
    /*----------------------------------------------------*/
    //  STA, Store Accumulator
    //  class: Writer
    //  Opcode: 0x95(149), Bytes: 2, Mode: ZeroPage_X
    //
    {   nmos_pre_w_zeropage_x, nmos_instr_STA },
    /*----------------------------------------------------*/
    //  STX, Store X Register
    //  class: Writer
    //  Opcode: 0x96(150), Bytes: 2, Mode: ZeroPage_Y
    //
    {   nmos_pre_w_zeropage_y, nmos_instr_STX },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x97(151)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  TYA, Transfer Y to Accumulator
    //  class: Regs
    //  Opcode: 0x98(152), Bytes: 1, Mode: Implied
    //
    {   nmos_instr_TYA, nmos_instr_TYA },
    /*----------------------------------------------------*/
    //  STA, Store Accumulator
    //  class: Writer
    //  Opcode: 0x99(153), Bytes: 3, Mode: Absolute_Y
    //
    {   nmos_pre_w_absolute_y, nmos_instr_STA },
    /*----------------------------------------------------*/
    //  TXS, Transfer X to Stack Pointer
    //  class: Regs
    //  Opcode: 0x9A(154), Bytes: 1, Mode: Implied
    //
    {   nmos_instr_TXS, nmos_instr_TXS },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x9B(155)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x9C(156)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  STA, Store Accumulator
    //  class: Writer
    //  Opcode: 0x9D(157), Bytes: 3, Mode: Absolute_X
    //
    {   nmos_pre_w_absolute_x, nmos_instr_STA },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x9E(158)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0x9F(159)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  LDY, Load Y Register
    //  class: Reader
    //  Opcode: 0xA0(160), Bytes: 2, Mode: Immediate
    //
    {   nmos_pre_r_immediate, nmos_instr_LDY },
    /*----------------------------------------------------*/
    //  LDA, Load Accumulator
    //  class: Reader
    //  Opcode: 0xA1(161), Bytes: 2, Mode: Indexed_X
    //
    {   nmos_pre_r_indexed_x, nmos_instr_LDA },
    /*----------------------------------------------------*/
    //  LDX, Load X Register
    //  class: Reader
    //  Opcode: 0xA2(162), Bytes: 2, Mode: Immediate
    //
    {   nmos_pre_r_immediate, nmos_instr_LDX },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xA3(163)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  LDY, Load Y Register
    //  class: Reader
    //  Opcode: 0xA4(164), Bytes: 2, Mode: ZeroPage
    //
    {   nmos_pre_r_zeropage, nmos_instr_LDY },
    /*----------------------------------------------------*/
    //  LDA, Load Accumulator
    //  class: Reader
    //  Opcode: 0xA5(165), Bytes: 2, Mode: ZeroPage
    //
    {   nmos_pre_r_zeropage, nmos_instr_LDA },
    /*----------------------------------------------------*/
    //  LDX, Load X Register
    //  class: Reader
    //  Opcode: 0xA6(166), Bytes: 2, Mode: ZeroPage
    //
    {   nmos_pre_r_zeropage, nmos_instr_LDX },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xA7(167)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  TAY, Transfer Accumulator to Y
    //  class: Regs
    //  Opcode: 0xA8(168), Bytes: 1, Mode: Implied
    //
    {   nmos_instr_TAY, nmos_instr_TAY },
    /*----------------------------------------------------*/
    //  LDA, Load Accumulator
    //  class: Reader
    //  Opcode: 0xA9(169), Bytes: 2, Mode: Immediate
    //
    {   nmos_pre_r_immediate, nmos_instr_LDA },
    /*----------------------------------------------------*/
    //  TAX, Transfer Accumulator to X
    //  class: Regs
    //  Opcode: 0xAA(170), Bytes: 1, Mode: Implied
    //
    {   nmos_instr_TAX, nmos_instr_TAX },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xAB(171)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  LDY, Load Y Register
    //  class: Reader
    //  Opcode: 0xAC(172), Bytes: 3, Mode: Absolute
    //
    {   nmos_pre_r_absolute, nmos_instr_LDY },
    /*----------------------------------------------------*/
    //  LDA, Load Accumulator
    //  class: Reader
    //  Opcode: 0xAD(173), Bytes: 3, Mode: Absolute
    //
    {   nmos_pre_r_absolute, nmos_instr_LDA },
    /*----------------------------------------------------*/
    //  LDX, Load X Register
    //  class: Reader
    //  Opcode: 0xAE(174), Bytes: 3, Mode: Absolute
    //
    {   nmos_pre_r_absolute, nmos_instr_LDX },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xAF(175)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  BCS, Branch if Carry Set
    //  class: BranchIf
    //  Opcode: 0xB0(176), Bytes: 2, Mode: Relative
    //
    {   nmos_instr_BCS, nmos_instr_BCS },
    /*----------------------------------------------------*/
    //  LDA, Load Accumulator
    //  class: Reader
    //  Opcode: 0xB1(177), Bytes: 2, Mode: Indexed_Y
    //
    {   nmos_pre_r_indexed_y, nmos_instr_LDA },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xB2(178)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xB3(179)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  LDY, Load Y Register
    //  class: Reader
    //  Opcode: 0xB4(180), Bytes: 2, Mode: ZeroPage_X
    //
    {   nmos_pre_r_zeropage_x, nmos_instr_LDY },
    /*----------------------------------------------------*/
    //  LDA, Load Accumulator
    //  class: Reader
    //  Opcode: 0xB5(181), Bytes: 2, Mode: ZeroPage_X
    //
    {   nmos_pre_r_zeropage_x, nmos_instr_LDA },
    /*----------------------------------------------------*/
    //  LDX, Load X Register
    //  class: Reader
    //  Opcode: 0xB6(182), Bytes: 2, Mode: ZeroPage_Y
    //
    {   nmos_pre_r_zeropage_y, nmos_instr_LDX },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xB7(183)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  CLV, Clear Overflow Flag
    //  class: Regs
    //  Opcode: 0xB8(184), Bytes: 1, Mode: Implied
    //
    {   nmos_instr_CLV, nmos_instr_CLV },
    /*----------------------------------------------------*/
    //  LDA, Load Accumulator
    //  class: Reader
    //  Opcode: 0xB9(185), Bytes: 3, Mode: Absolute_Y
    //
    {   nmos_pre_r_absolute_y, nmos_instr_LDA },
    /*----------------------------------------------------*/
    //  TSX, Transfer Stack Pointer to X
    //  class: Regs
    //  Opcode: 0xBA(186), Bytes: 1, Mode: Implied
    //
    {   nmos_instr_TSX, nmos_instr_TSX },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xBB(187)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  LDY, Load Y Register
    //  class: Reader
    //  Opcode: 0xBC(188), Bytes: 3, Mode: Absolute_X
    //
    {   nmos_pre_r_absolute_x, nmos_instr_LDY },
    /*----------------------------------------------------*/
    //  LDA, Load Accumulator
    //  class: Reader
    //  Opcode: 0xBD(189), Bytes: 3, Mode: Absolute_X
    //
    {   nmos_pre_r_absolute_x, nmos_instr_LDA },
    /*----------------------------------------------------*/
    //  LDX, Load X Register
    //  class: Reader
    //  Opcode: 0xBE(190), Bytes: 3, Mode: Absolute_Y
    //
    {   nmos_pre_r_absolute_y, nmos_instr_LDX },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xBF(191)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  CPY, Compare Y Register
    //  class: Reader
    //  Opcode: 0xC0(192), Bytes: 2, Mode: Immediate
    //
    {   nmos_pre_r_immediate, nmos_instr_CPY },
    /*----------------------------------------------------*/
    //  CMP, Compare
    //  class: Reader
    //  Opcode: 0xC1(193), Bytes: 2, Mode: Indexed_X
    //
    {   nmos_pre_r_indexed_x, nmos_instr_CMP },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xC2(194)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xC3(195)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  CPY, Compare Y Register
    //  class: Reader
    //  Opcode: 0xC4(196), Bytes: 2, Mode: ZeroPage
    //
    {   nmos_pre_r_zeropage, nmos_instr_CPY },
    /*----------------------------------------------------*/
    //  CMP, Compare
    //  class: Reader
    //  Opcode: 0xC5(197), Bytes: 2, Mode: ZeroPage
    //
    {   nmos_pre_r_zeropage, nmos_instr_CMP },
    /*----------------------------------------------------*/
    //  DEC, Decrement Memory
    //  class: ReaderWriter
    //  Opcode: 0xC6(198), Bytes: 2, Mode: ZeroPage
    //
    {   nmos_pre_rw_zeropage, nmos_instr_DEC },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xC7(199)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  INY, Increment Y Register
    //  class: Regs
    //  Opcode: 0xC8(200), Bytes: 1, Mode: Implied
    //
    {   nmos_instr_INY, nmos_instr_INY },
    /*----------------------------------------------------*/
    //  CMP, Compare
    //  class: Reader
    //  Opcode: 0xC9(201), Bytes: 2, Mode: Immediate
    //
    {   nmos_pre_r_immediate, nmos_instr_CMP },
    /*----------------------------------------------------*/
    //  DEX, Decrement X Register
    //  class: Regs
    //  Opcode: 0xCA(202), Bytes: 1, Mode: Implied
    //
    {   nmos_instr_DEX, nmos_instr_DEX },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xCB(203)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  CPY, Compare Y Register
    //  class: Reader
    //  Opcode: 0xCC(204), Bytes: 3, Mode: Absolute
    //
    {   nmos_pre_r_absolute, nmos_instr_CPY },
    /*----------------------------------------------------*/
    //  CMP, Compare
    //  class: Reader
    //  Opcode: 0xCD(205), Bytes: 3, Mode: Absolute
    //
    {   nmos_pre_r_absolute, nmos_instr_CMP },
    /*----------------------------------------------------*/
    //  DEC, Decrement Memory
    //  class: ReaderWriter
    //  Opcode: 0xCE(206), Bytes: 3, Mode: Absolute
    //
    {   nmos_pre_rw_absolute, nmos_instr_DEC },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xCF(207)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  BNE, Branch if Not Equal
    //  class: BranchIf
    //  Opcode: 0xD0(208), Bytes: 2, Mode: Relative
    //
    {   nmos_instr_BNE, nmos_instr_BNE },
    /*----------------------------------------------------*/
    //  CMP, Compare
    //  class: Reader
    //  Opcode: 0xD1(209), Bytes: 2, Mode: Indexed_Y
    //
    {   nmos_pre_r_indexed_y, nmos_instr_CMP },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xD2(210)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xD3(211)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xD4(212)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  CMP, Compare
    //  class: Reader
    //  Opcode: 0xD5(213), Bytes: 2, Mode: ZeroPage_X
    //
    {   nmos_pre_r_zeropage_x, nmos_instr_CMP },
    /*----------------------------------------------------*/
    //  DEC, Decrement Memory
    //  class: ReaderWriter
    //  Opcode: 0xD6(214), Bytes: 2, Mode: ZeroPage_X
    //
    {   nmos_pre_rw_zeropage_x, nmos_instr_DEC },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xD7(215)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  CLD, Clear Decimal Mode
    //  class: Regs
    //  Opcode: 0xD8(216), Bytes: 1, Mode: Implied
    //
    {   nmos_instr_CLD, nmos_instr_CLD },
    /*----------------------------------------------------*/
    //  CMP, Compare
    //  class: Reader
    //  Opcode: 0xD9(217), Bytes: 3, Mode: Absolute_Y
    //
    {   nmos_pre_r_absolute_y, nmos_instr_CMP },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xDA(218)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xDB(219)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xDC(220)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  CMP, Compare
    //  class: Reader
    //  Opcode: 0xDD(221), Bytes: 3, Mode: Absolute_X
    //
    {   nmos_pre_r_absolute_x, nmos_instr_CMP },
    /*----------------------------------------------------*/
    //  DEC, Decrement Memory
    //  class: ReaderWriter
    //  Opcode: 0xDE(222), Bytes: 3, Mode: Absolute_X
    //
    {   nmos_pre_rw_absolute_x, nmos_instr_DEC },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xDF(223)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  CPX, Compare X Register
    //  class: Reader
    //  Opcode: 0xE0(224), Bytes: 2, Mode: Immediate
    //
    {   nmos_pre_r_immediate, nmos_instr_CPX },
    /*----------------------------------------------------*/
    //  SBC, Subtract with Carry
    //  class: Reader
    //  Opcode: 0xE1(225), Bytes: 2, Mode: Indexed_X
    //
    {   nmos_pre_r_indexed_x, nmos_instr_SBC },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xE2(226)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xE3(227)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  CPX, Compare X Register
    //  class: Reader
    //  Opcode: 0xE4(228), Bytes: 2, Mode: ZeroPage
    //
    {   nmos_pre_r_zeropage, nmos_instr_CPX },
    /*----------------------------------------------------*/
    //  SBC, Subtract with Carry
    //  class: Reader
    //  Opcode: 0xE5(229), Bytes: 2, Mode: ZeroPage
    //
    {   nmos_pre_r_zeropage, nmos_instr_SBC },
    /*----------------------------------------------------*/
    //  INC, Increment Memory
    //  class: ReaderWriter
    //  Opcode: 0xE6(230), Bytes: 2, Mode: ZeroPage
    //
    {   nmos_pre_rw_zeropage, nmos_instr_INC },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xE7(231)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  INX, Increment X Register
    //  class: Regs
    //  Opcode: 0xE8(232), Bytes: 1, Mode: Implied
    //
    {   nmos_instr_INX, nmos_instr_INX },
    /*----------------------------------------------------*/
    //  SBC, Subtract with Carry
    //  class: Reader
    //  Opcode: 0xE9(233), Bytes: 2, Mode: Immediate
    //
    {   nmos_pre_r_immediate, nmos_instr_SBC },
    /*----------------------------------------------------*/
    //  NOP, No Operation
    //  class: Special
    //  Opcode: 0xEA(234), Bytes: 1, Mode: Implied
    //
    {   nmos_instr_NOP, nmos_instr_NOP },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xEB(235)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  CPX, Compare X Register
    //  class: Reader
    //  Opcode: 0xEC(236), Bytes: 3, Mode: Absolute
    //
    {   nmos_pre_r_absolute, nmos_instr_CPX },
    /*----------------------------------------------------*/
    //  SBC, Subtract with Carry
    //  class: Reader
    //  Opcode: 0xED(237), Bytes: 3, Mode: Absolute
    //
    {   nmos_pre_r_absolute, nmos_instr_SBC },
    /*----------------------------------------------------*/
    //  INC, Increment Memory
    //  class: ReaderWriter
    //  Opcode: 0xEE(238), Bytes: 3, Mode: Absolute
    //
    {   nmos_pre_rw_absolute, nmos_instr_INC },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xEF(239)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  BEQ, Branch if Equal
    //  class: BranchIf
    //  Opcode: 0xF0(240), Bytes: 2, Mode: Relative
    //
    {   nmos_instr_BEQ, nmos_instr_BEQ },
    /*----------------------------------------------------*/
    //  SBC, Subtract with Carry
    //  class: Reader
    //  Opcode: 0xF1(241), Bytes: 2, Mode: Indexed_Y
    //
    {   nmos_pre_r_indexed_y, nmos_instr_SBC },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xF2(242)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xF3(243)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xF4(244)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  SBC, Subtract with Carry
    //  class: Reader
    //  Opcode: 0xF5(245), Bytes: 2, Mode: ZeroPage_X
    //
    {   nmos_pre_r_zeropage_x, nmos_instr_SBC },
    /*----------------------------------------------------*/
    //  INC, Increment Memory
    //  class: ReaderWriter
    //  Opcode: 0xF6(246), Bytes: 2, Mode: ZeroPage_X
    //
    {   nmos_pre_rw_zeropage_x, nmos_instr_INC },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xF7(247)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  SED, Set Decimal Flag
    //  class: Regs
    //  Opcode: 0xF8(248), Bytes: 1, Mode: Implied
    //
    {   nmos_instr_SED, nmos_instr_SED },
    /*----------------------------------------------------*/
    //  SBC, Subtract with Carry
    //  class: Reader
    //  Opcode: 0xF9(249), Bytes: 3, Mode: Absolute_Y
    //
    {   nmos_pre_r_absolute_y, nmos_instr_SBC },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xFA(250)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xFB(251)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xFC(252)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL },
    /*----------------------------------------------------*/
    //  SBC, Subtract with Carry
    //  class: Reader
    //  Opcode: 0xFD(253), Bytes: 3, Mode: Absolute_X
    //
    {   nmos_pre_r_absolute_x, nmos_instr_SBC },
    /*----------------------------------------------------*/
    //  INC, Increment Memory
    //  class: ReaderWriter
    //  Opcode: 0xFE(254), Bytes: 3, Mode: Absolute_X
    //
    {   nmos_pre_rw_absolute_x, nmos_instr_INC },
    /*----------------------------------------------------*/
    //  OPCODE INVALID
    //  Opcode: 0xFF(255)
    //
    {   nmos_instr_ILLEGAL, nmos_instr_ILLEGAL }
    /*----------------------------------------------------*/
}
};
#endif // QE6502_NMOS_OPCODES_H__

